# docker-compose.yml
version: '3.8'

services:
  coreapp:
    container_name: admin
    build: .
    ports:
      - "3000:3000"
    environment:
      - SKIP_PREFLIGHT_CHECK=true
      - DISABLE_ESLINT_PLUGIN=true
